version: '3'
name: queue-jobs
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
  php:
    build: ./
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      - db
    ports:
      - '8080:80'
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
volumes:
  db_data:
